### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by aschrijver** [kaniini/jejune#1]
Hi @kaniini 

Fantastic to see yet another AP project underway! We added the project to the [AP watchlist](https://git.feneas.org/feneas/fediverse/-/wikis/watchlist-for-activitypub-apps/diff?version_id=c67246457a3f7375743de4c547d6b927aea8dd4c), and regarding to that I have one question re:licensing.

Am I correct in stating that the way your COPYING.md is worded, means this project is effectively MIT licensed?

**Comment by Minoru** [comment]
It looks like an ISC license to me, although the disclaimer is shortened and put in ordinary case.

**Comment by aschrijver** [comment]
Oh yes, hadn't considered [ISC](https://en.wikipedia.org/wiki/ISC_license). Thanks.

**Comment by kaniini** [comment]
Yes, it's ISC license, with a modified warranty disclaimer.

**Comment by kaniini** [comment]
By the way, Jejune is federating already and some brave people are even using it in production.

**Comment by aschrijver** [comment]
Thanks! I updated the list.
